GET http://localhost:3003/ping
###

GET http://localhost:3003/users
###

GET http://localhost:3003/products
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "us005",
    "name": "Tina",
    "email": "tina@email.com",
    "password": "19135784"
}
###

POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "pro009",
    "name": "Escrivaninha Regulável",
    "price": 499,
    "description": "Escrivaninha regulável",
    "imageUrl": "Image"
}
###

GET http://localhost:3003/purchases
###

GET http://localhost:3003/purchases/pur04
###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "id": "pur04",
    "buyer": "us004",
    "total_price": "199.99"
}
###

PUT http://localhost:3003/products/pro007
Content-Type: application/json

{
    "newId": "pro007",
    "newName": "Home Theater",
    "newPrice": 1199,
    "newDescription": "Caixa de Som 2.1 Subwoofer",
    "newImageUrl": "Image"
}
###

DELETE http://localhost:3003/purchases/pur04
###
